### ISSUE TITLE
Different match depending of punctuation 

### ISSUE THREAD

**Issue by piitaya** [home-assistant/hassil#143]
Intent matching can be different with different punctation. It should be the same. Sometimes, STT adds comma to the sentences and it can lead to different intent matching.
Here's some examples in french using comma. I tested those sentences using Home Assistant.

**Allume la lumière du salon**
`<allume> [<tous>] [<le>](<lumiere>|<lumieres>) [<dans>] [<le>]{area}` ✅

**Allume, la lumière du salon** 
`<allume> [<le>]{name}` ❌

**,Allume, la lumière du salon**
`<allume> [<tous>] [<le>](<lumiere>|<lumieres>) [<dans>] [<le>]{area}` ✅

**Comment by jlpouffier** [comment]
We are very unlucky to get this one (IT also happens to me constantly... That coma in that particular place)
It happens with HA Cloud STT.

We're very unlucky because HASSIL seems to stripe almost everything down in any other cases...

![CleanShot 2024-06-19 at 13 26 20](https://github.com/home-assistant/hassil/assets/5878296/e036f314-4d79-4e43-a59c-2d8527effcd1)
