### ISSUE TITLE
random string in custom intent

### ISSUE THREAD

**Issue by siemon-geeroms** [home-assistant/hassil#47]
Hi,

I have a question, why can't a random string be used as part of an intent as was the case with the text ingredient option in IFTTT ? Let me clarify with an example.

I would like to create a custom intent that will add some stuff to a shopping list via a service call in home assistant.

However now I need to define a fixed list of items that can appear in the sentence. 

In my opinion it should be possible to setup a custom sentence like this: "add \<text\> to my shopping list". the text part will then be passed along to the intent_script which then can use this as, for example, a variable when calling a script.

I can imagine that there would be more false positive/negatives this way but that should be something people should be aware of when using this functionality.

**Comment by synesthesiam** [comment]
This is something that will require changes to the algorithm, but it is planned to be added (specifically for shopping lists).

**Comment by Nold360** [comment]
Damn, i just made a really cool node-red flow & wanted to trigger it using intents.. T_T

Can't wait for this feature!

**Comment by michaelblight** [comment]
> Can't wait for this feature

In the meantime I am using a temporary workable solution. And for anybody that's foolish enough to do the same...

I copied the [conversation](https://github.com/home-assistant/core/tree/dev/homeassistant/components/conversation) files to "/config/custom_components/conversation", and then changed line 184 in "default_agent.py" to be "warning" rather than "debug".

Then I put the following in "configuration.yaml" so that warnings and errors would generate an event.
```
system_log:
  max_entries: 200
  fire_event: true
```
After a restart, Node Red can listen "system_log_event" using an `events: all` node. If you say something like "buy white bread", which HA doesn't understand, it will now fire an event including "No intent was matched for ' Bye! White bread!'". So you can extract the part in single quotes and deal with "buy" vs "bye" vs "by" (and even sometimes "five" and "byebye").

Obviously HA is still going to say "I don't understand", but I'm using an old-style telephone and I hang up before that happens.

You also need to deal with the fact that "default_agent.py" is likely to change and you have to update manually. I'm tempted to automate tracking changes for this file, if it goes on for long enough.

**Comment by siemon-geeroms** [comment]
hi I've created a agent that can parse regex sentences to trigger custom intents. when no matches found the default agent will be triggered. Have a look here: [https://github.com/siemon-geeroms/yarvis](https://github.com/siemon-geeroms/yarvis). you can add it as a custom integration via the hacs store. just need to add my repo as a custom repo. please be aware the is my first attempt to write a custom component and in early stages of development

**Comment by synesthesiam** [comment]
Wildcards are being added here: https://github.com/home-assistant/hassil/pull/56
